package:
  name: __PROJNAME__-tangent
  version: "0.0.1"
about:
  home: https://github.com/tangent-reckon/__PROJNAME__
  license: MIT
  summary: '[tbd]'
source:
  fn: __PROJNAME__-tangent-0.0.1.tar.gz
    # url: https://test.pypi.org/packages/source/s/sampleproject-YOUR-USERNAME/sampleproject-YOUR-USERNAME-0.0.1.tar.gz
  md5: "run md5sum dist/__PROJ_NAME-tangent-0.0.1.tar.gz to obtain the md5 hash"

requirements:
  build:
    - pip >=22
    - python >=3.10
  run:
    - python >=3.10
